apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: rational-gibbon-nodejs 
  janus-idp.io/tekton: rational-gibbon-nodejs
  backstage.io/kubernetes-id: rational-gibbon-nodejs
  backstage.io/kubernetes-namespace: rhtap-e2e-ci 
  app.kubernetes.io/part-of: rational-gibbon-nodejs
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  